
[duration=10m]
== Spring Boot

// JPA, REST, Stormpath and Cloud Foundry demo

////
1. Create new project with start.spring.io, choose Web, JPA and DevTools
1. @Entity, @Id, @GeneratedValue / toString / getters and setters - **boot.entity**
1. interface BlogRepository extends JpaRepository<Blog, Long> {} - **boot.repository**
1. implements CommandLineRunner, println repository.findAll() - **boot.command**
1. Add JDBC Driver to pom.xml: **boot.h2**
1. create data.sql, insert into blog (name) values ('First'); - **boot.sql**
1. @RestController, @RequestMapping, return repository.findAll() - **boot.controller**
////

include::{uri-demos}/spring-boot/README.adoc[]

[duration=5m]
== JHipster

https://jhipster.github.io/[JHipster] is one of those open-source projects you stumble upon and immediately think, "`Of course!`" It combines three very successful frameworks in web development: Bootstrap, AngularJS, and Spring Boot. Bootstrap was one of the first dominant web-component frameworks. Its largest appeal was that it only required a bit of HTML and it worked! All the efforts we made in the Java community to develop web components were shown a better path by Bootstrap. It leveled the playing field in HTML/CSS development, much like Apple's Human Interface Guidelines did for iOS apps.

JHipster was started by Julien Dubois in October 2013 (Julien's first commit was on https://github.com/jhipster/generator-jhipster/commit/c8630ab7af7b6a99db880b3b0e2403806b7d2436[October 21, 2013]). The first public release (version 0.3.1) was launched December 7, 2013. Since then, the project has had over 110 releases! It is an open-source, Apache 2.0-licensed project on GitHub. It has a core team of 16 developers and over 250 contributors. You can find its homepage at http://jhipster.github.io/[http://jhipster.github.io]. Its https://www.openhub.net/p/generator-jhipster[Open HUB profile] shows it's mostly written in JavaScript (50%) and Java (35%).

At its core, JHipster is a http://yeoman.io/[Yeoman] generator. Yeoman is a code generator that you run with a `yo` command to generate complete applications or useful pieces of an application. Yeoman generators promote what the Yeoman team calls the "`Yeoman workflow`". This is an opinionated client-side stack of tools that can help developers quickly build beautiful web applications. It takes care of providing everything needed to get working without the normal pains associated with a manual setup.

////
The Yeoman workflow is made up of three types of tools to enhance your productivity and satisfaction when building a webapp:

* the scaffolding tool (yo),
* the build tool (Grunt, Gulp, etc.), and
* the package manager (Bower, npm, etc.)
////
// tag::jhipster[]

==== JHipster Statistics

* Fully Open Source
* +250 contributors
* +5300 Github stars
* +320,000 installations
* +100 companies officially using it
// end::jhipster[]

=== JHipster Toolchain / Workflow

To https://jhipster.github.io/installation/[install] JHipster, you run an npm command:

----
npm install -g generator-jhipster
----

You also skip installation and use the project's https://hub.docker.com/r/jhipster/jhipster/[Official JHipster Docker image] or https://github.com/jhipster/jhipster-devbox[JHipster Devbox] instead.

Next, you run `yo jhipster` to create an application. You will be presented with a number of questions. Your answers will generate an application tailored to your needs.

----
> mkdir myapp && cd myapp
> yo jhipster
----

The JHipster documentation includes https://jhipster.github.io/configuring-ide/[guides] for configuring Eclipse, IntelliJ IDEA, Visual Studio Code, and NetBeans. Not only that, but Spring Boot has a https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html[devtools plugin] that's configured by default in a generated JHipster application. This plugin allows hot-reloading of your application when you recompile classes.

https://www.jetbrains.com/idea/[IntelliJ IDEA], which brings these same features to Java development, is a truly amazing IDE. If you're only writing JavaScript, their https://www.jetbrains.com/webstorm/[WebStorm IDE] will likely become your best friend. Both IntelliJ products have excellent CSS support and accept plugins for many web languages/frameworks. See https://github.com/jhipster/generator-jhipster/issues/4258[this tip] to learn how to make IDEA auto-compile on save, like Eclipse does.

The http://www.eclipse.org/downloads/packages/eclipse-ide-java-developers/neon1[Eclipse IDE for Java Developers] is a free alternative to IntelliJ IDEA. Its error highlighting (via auto-compile), code assist, and refactoring support is excellent. When I started using it back in 2002, it blew away the competition. It was the first Java IDE that was fast and efficient to use. Unfortunately, it fell behind in the JavaScript MVC era and lacks good support for JavaScript or CSS.

NetBeans has a https://github.com/GeertjanWielenga/SpringBootTools4NetBeans[Spring Boot plugin]. The NetBeans team has been doing a lot of work on web-tools support; they have good JavaScript/AngularJS support and there's a https://chrome.google.com/webstore/detail/netbeans-connector/hafdlehgocfcodbgjnpecfajgkeejnaa?hl=en[NetBeans Connector] plugin for Chrome that allows two-way editing in NetBeans and Chrome.

https://code.visualstudio.com[Visual Studio Code] is an open source text editor made by Microsoft. It's become a popular editor for TypeScript and has plugins for Java development.

The beauty of Spring Boot is you can run it as a simple Java process. This means you can right-click on your `*Application.java` class and run it (or debug it) from your IDE. When debugging, you'll be able to set breakpoints in your Java classes and see what variables are being set to before a process executes.

To learn about profiling a Java application, I recommend you watch Nitsan Wakart's https://www.youtube.com/watch?v=_6vJyciXkwo["`Java Profiling from the Ground Up!`"] To learn more about memory and JavaScript applications, I recommend Addy Osmani's http://addyosmani.com/blog/video-javascript-memory-management-masterclass/["`JavaScript Memory Management Masterclass`"].

=== What's Generated?

* Spring Boot application
* AngularJS application
* Liquibase changelog files
* Configuration files

==== Generated Screens for Security

* Several generated screens
** Login, logout, forgot password…
** Account management
** User management
* Useful for most applications
** Pages must be tuned depending on business needs
** User roles will be added/extended
* Provide also good examples of working screens
** Forms, directives, validation...

==== Generated Screens for Administration

* Administration screens
** Monitoring
* Health
** Spring Boot configuration
** Spring Security audits
** Log management
* Very useful in production
* Will likely be a separate module in JHipster 4

==== Liquibase

* Liquibase manages database updates
** Using changelogs
* Great for working in team
** After a “git pull”, your database is always up-to-date!
* Tables, relationships, data are all created by JHipster at generation time, and applied when the application starts

==== Many other features!

* Maven or Gradle
* Docker and Docker Compose
* SQL and NoSQL databases
// MongoDB and Cassandra
* Elasticsearch
* Kafka
* Internationalization
* Swagger
* WebSockets
* CRUD Generation
* Modules and Marketplace

Be Productive with JHipster by Julien Dubois and Deepu K
https://www.youtube.com/watch?v=dzdjP3CPOCs

[duration=30m]
== JHipster Demo

JHipster provides a flow-invoking developer experience.

* “Developer Experience” is very important for JHipster
* Hot reload should work everywhere
* IDEs should work automatically
* Docker Compose for all 3rd-party tools, so they are easy to manage

A lot of credit goes to Spring Boot devtools!

* Automatically reloads the application when a compilation occurs
** The application classloader gets refreshed
** The JVM and third-party libraries are not refreshed
* Hot reload is very quick: 2 to 4 seconds depending on your setup
* Liquibase being managed by JHipster, the database schema is also automatically updated

[TIP]
Configure your IDE to do automatic compilation, and everything is updated automatically!

////
// JHipster blog demo howto (use yarn)
Lock it down so people can’t see each other’s data
Modify tests so they pass
Show Liquibase:diff
Commit to GitHub as you go
Deploy to Heroku
////
include::{uri-demos}/jhipster-monolith/README.adoc[]

=== Microservices with JHipster

// https://docs.google.com/document/d/1Wxo43oJgp4XP-C72pIbT-cjV0S4OlAHHAxxt7bgXFHw/edit#heading=h.ph7yfcmesusl

What about Microservices?
Show architecture diagram from Devoxx

Fire up JHipster Registry (:8761)
Change it to be a gateway and re-generate
Create a new micro services app with a store
Use JDL Studio and import to generate entities

include::{uri-demos}/jhipster-microservices/README.adoc[tag=main]

[duration=20m]
== Securing your API

https://stormpath.com/blog/secure-your-rest-api-right-way

// token-based auth

=== HTTPS Even for internal

Let's Encrypt

=== Docker containers can have vulnerability

https://github.com/coreos/clair

=== OAuth 2

https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2

=== Open ID Connect

https://www.youtube.com/watch?v=Kb56GzQ2pSk&feature=youtu.be

=== JWT

https://stormpath.com/blog/beginners-guide-jwts-in-java
https://stormpath.com/blog/jwt-the-right-way
https://stormpath.com/blog/build-secure-user-interfaces-using-jwts
https://stormpath.com/blog/jwt-authentication-angularjs

// Micah's demo
https://www.youtube.com/watch?v=QSYK4OCmycIs

// Mention how Stormpath uses JWT

==== JWT Tools

https://github.com/jwtk/jjwt[JJWT] is an easy to use tool for developers to create and verify JWTs in Java. Like many libraries Stormpath supports, JJWT is completely free and open source (Apache License, Version 2.0), so everyone can see what it does and how it does it. Do not hesitate to report any issues, suggest improvements, and even submit some code!

https://www.jsonwebtoken.io/[JSONwebtoken.io] is a developer tool we created to make it easy to decode JWTs. Simple paste an existing JWT into the appropriate field to decode its header, payload, and signature. JSONWebToken.io is powered by nJWT, the cleanest free and open source (Apache License, Version 2.0) JWT library for Node.js developers.

https://www.jwtinspector.io/[JWT Inspector] is the new kid on the block; it's an open source Chrome extension that allows developers to inspect and debug JWTs directly in-browser. The JWT Inspector will discover JWTs on your site (in cookies, local/session storage, and headers) and make them easily accessible through your navigation bar and DevTools panel.

=== JHipster Security Options

* Session-based authentication
** Stateful
** Classical “form-based” authentication with Spring Security
** Improved remember-me over the standard Spring Security implementation
* OAuth2
** Stateless
** Needs a specific back-end, only works with SQL and MongoDB
* JWT
** Stateless
** Very good for microservices


// Zuul with JHipster Registry/Consul?
// JHipster UAA

=== Demo

Create a UAA service for Auth
Show JWT communicate and explain key registration


[duration=2]
== Conclusion

Microservices aren't free, but they're cheaper if you start with JHipster!

[duration=1m]
== Action!

[duration=5m]
== Questions?

== Resources

https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage
