// tag::main[]
= JHipster Microservices Demo
:imagesdir: ../../presentation/src/images

To reproduce this demo, delete everything in this directory except for this file.

. Copy `jhipster-monolith` and paste it to `jhipster-microservices/blog`. Change the following value in `.yo-rc.json`:
+
[source,json]
----
"applicationType": "gateway"
"serviceDiscoveryType": "eureka"
----
. Regenerate application using `yo jhipster --with-entities`.
. Using Git, re-apply business logic changes.
. Create a new directory called `store` and run `yo jhipster` in it to create a "store" microservice. Use Maven, MongoDB, and Kafka.
. Generate a `product` entity with a name and a price.
. Generate the UI for the store using `yo jhipster:entity product` from the `blog` directory.
. Clone JHipster Registry: `git clone git@github.com:jhipster/jhipster-registry.git`.
. Start MongoDB and Kafka using Docker Compose.
* Store: 
** `docker-compose -f src/main/docker/mondodb.yml up`
** `docker-compose -f src/main/docker/kafka.yml up`
** `./mvnw`
* Blog: `./gradlew`
* Registry: `./mvnw`

[TIP]
====
To remove all docker containers, run the following commands or do it manually using Kitematic.
----
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
----
To find what's running on a port on OS, use `sudo lsof -i :9092 # checks port 9092`.
====
// end::main[]

// tag::deploy[]
== Docker Compose
. Install https://docs.docker.com/engine/installation/[Docker] and https://docs.docker.com/compose/install/[Docker Compose].
. Create Docker images of the `blog` and `store` applications:
* Maven: `./mvnw package -Pprod docker:build`
* Gradle: `./gradlew bootRepackage -Pprod buildDocker`
. Create a `docker-compose` directory and run `yo jhipster:docker-compose` from it.
. Start Docker.
. Run `docker-compose up -d` to run everything.
. Start Kitematic and view Docker applications.

== Kubernetes
. Install https://docs.docker.com/engine/installation/[Docker] and http://kubernetes.io/docs/user-guide/prereqs/[kubectl].
. Install https://www.virtualbox.org/wiki/Downloads[VirtualBox] and https://github.com/kubernetes/minikube/releases[Minikube].
. Start Minikube using `minikube start`.
. To be able to work with the docker daemon, run the `docker-env` command in your shell:

  eval $(minikube docker-env)

. Create Docker images of the `blog` and `store` applications:
* Maven: `./mvnw package -Pprod docker:build`
* Gradle: `./gradlew bootRepackage -Pprod buildDocker`
. Create a `kubernetes` directory and run `yo jhipster:kubernetes` from it.
. Modify `kubernetes/blog/blog-deployment.yml` to add `imagePullPolicy: IfNotPresent`.

  image: blog
  imagePullPolicy: IfNotPresent

. Modify `kubernetes/store/store-deployment.yml` to add `imagePullPolicy: IfNotPresent`.

  image: store
  imagePullPolicy: IfNotPresent

. Run the following commands to deploy to Minikube. Run `minikube dashboard` to see the deployed containers.

  kubectl apply -f registry
  kubectl apply -f blog
  kubectl apply -f store

. Run `minikube service blog` to view the blog application. You can also run `kubectl get po -o wide --watch` to see the status of each pod.

[TIP]
If you run `minikube delete` and have trouble running `minikube start` afterward, run `rm -rf ~/.minikube`. See https://github.com/kubernetes/minikube/issues/290[this issue] for more information.
// end::deploy[]

// kubectl delete deployment --all

// http://kubernetes.io/docs/user-guide/kubectl/kubectl_delete/
// todo: figure out how to deploy Docker containers to Amazon ECS - https://aws.amazon.com/blogs/aws/cloud-container-management/
// todo: figure out how to deploy with Kubernetes to Google Cloud - https://cloud.google.com/container-engine/docs/
