= Microservices for the Masses with Spring Boot, JHipster, and JWT
Matt Raible <https://github.com/mraible[@mraible]>
:branch: master

[abstract]
--
// tag:abstract[]
Microservices are all the rage and being deployed by many Java Hipsters. If you’re working on a large team that needs different release cycles for product components, microservices can be a blessing. If you’re working at your VW Restoration Shop and running its online store with your own software, having five services to manage and deploy can be a real pain. Share your knowledge and experience about microservices in this informative and code-heavy talk.

We’ll use JHipster (a Yeoman generator) to create Angular + Spring Boot apps on separate instances with a unified front-end. I’ll also show you options for securing your API gateway and individual applications using JWT. Heroku, Kubernetes, Docker, ELK, Spring Cloud, Stormpath; there will be plenty of interesting demos to see!
// end:abstract[]
--

== View online

https://mraible.github.io/microservices-for-the-masses[Slides]
//&middot;
//https://github.com/mraible/microservices-for-the-masses/blob/{branch}/src/notes/script.adoc[Script]

=== Demos

* https://github.com/mraible/microservices-for-the-masses/blob/{branch}/demos/spring-boot/README.adoc[Spring Boot]
* https://github.com/mraible/microservices-for-the-masses/blob/{branch}/demos/jhipster-monolith/README.adoc[JHipster Monolith]
* https://github.com/mraible/microservices-for-the-masses/blob/{branch}/demos/jhipster-microservices/README.adoc[JHipster Microservices]

== Build and view slides locally

First, ensure you have the following installed:

. http://nodejs.org[Node.js]
. http://gulpjs.com[Gulp CLI]

 $ npm install -g gulp-cli

. https://www.ruby-lang.org/[Ruby >= 2]

 $ rvm use 2.3.1 --install

. http://bundler.io/[Bundler]

 $ gem install bundler

Next, install dependencies (if not already installed by the generator):

 $ npm install
   bundle install --path=.bundle/gems

Finally, build and serve the presentation!

 $ gulp serve

== Building the static version

You can build a static version of the slides using the following command:

 $ gulp

The files are built into the _dist_ directory.
You can then view the slides by navigating to _dist/index.html_ in your browser.

== Deploy static version

You can publish to GitHub pages by running the following command:

  $ gulp deploy

== Tips and Tricks

You can export the presentation to PDF using https://github.com/astefanutti/decktape[DeckTape].